version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/react-app

hooks:
  ApplicationStart:
    - location: ""
      timeout: 600
      runas: ec2-user
      commands:
        - cd /home/ec2-user/react-app
        - echo "Stopping old container..."
        - docker stop react-container || true
        - docker rm react-container || true
        - echo "Installing dependencies..."
        - npm install
        - echo "Building React app..."
        - npm run build
        - echo "Building Docker image..."
        - docker build -t react-pipeline .
        - echo "Running container..."
        - docker run -d --name react-container -p 80:3000 react-pipeline
