version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/react-app

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
