version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
hooks:
  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 60
  AfterInstall:
    - location: scripts/build_image.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
