version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t react-pipeline .
      - docker tag react-pipeline:latest <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/react-pipeline:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/react-pipeline:latest
      - echo Deploying to EC2...
      - ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> "docker pull <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/react-pipeline:latest && docker stop react-container || true && docker rm react-container || true && docker run -d --name react-container -p 80:3000 <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/react-pipeline:latest"
